[package]
name = "volcano_addon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi 		= { version = "2.10.1", default-features = false, features = ["napi6", "tokio_rt"] }
napi-derive = "2.9.1"
reqwest 	= "0.11.12"
env_logger  = "0.10.0"

[dependencies.symphonia]
features = ["aac", "mp3", "isomp4", "alac", "mkv"] # ...as well as any extras you need!
git = "https://github.com/FelixMcFelix/Symphonia"
branch = "songbird-fixes"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
