name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install, Lint, Compile, and create build info for server
        run: |
          rm ./.yarnrc.yml
          mv ./.yarnrc.nopath.yml ./.yarnrc.yml
          yarn set version 3.3.0
          yarn install
          yarn run lint
          npm --prefix ./packages/server run build
          npm --prefix ./packages/server run create-release

      - uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: |
            package.json
            packages/server/dist/
            packages/server/scripts/
            LICENSE
            packages/server/package.json
            PLUGINS.md
            PUBLIC_SERVERS.md
            README.md

      - uses: actions/upload-artifact@v3
        with:
          name: sdk-artifact
          path: |
            package.json
            packages/sdk/index.d.ts
            packages/sdk/index.js
            packages/sdk/package.json
            packages/sdk/README.md
            packages/sdk/server-utils.d.ts
            packages/sdk/types.d.ts
